--- 
  - name: Discover play 
    hosts: all 
    gather_facts: true 
    tasks: 
       - name: Finding os name 
         shell: "uname"
         register: os_name 
       - name: Finding uptime 
         shell: 'uptime'
         register: up_time 
       - name: Display Discovery info 
         debug:  
            msg: "{{inventory_hostname}},{{ansible_system}},{{ansible_os_family}},{{os_name.stdout}},{{up_time.stdout.split(',')[0].split('up')[-1]}}"
        #create empty csv file
       - name: Removing old discovery.csv file
         file:
            dest: ./Discovery.csv
            state: absent
          delegate_to: 
       - name: Creating the Discovery.scv file
         copy:
            dest: ./Discovery.csv
            content: "Sever_name, OS Family, OS Name, OS Distribution, uptime"
         delegate_to: 172.17.0.2
         run_once: true 